BSM_ERRORS = {
    0: "success",
    1: "Operation not permitted",
    2: "No sch file or directory",
    3: "No sch process",
    4: "Interrpted system call",
    5: "Inpt/otpt error",
    6: "Device not configred",
    7: "Argment list too long",
    8: "Exec format error",
    9: "Bad file descriptor",
    10: "No child processes",
    11: "Resorce temporarily navailable",
    12: "Cannot allocate memory",
    13: "Permission denied",
    14: "Bad address",
    15: "Block device reqired",
    16: "Device bsy",
    17: "File exists",
    18: "ross-device link",
    19: "Operation not spported by device",
    20: "Not a directory",
    21: "Is a directory",
    22: "Invalid argment",
    23: "Too many open files in system",
    24: "Too many open files",
    25: "Inappropriate ioctl for device",
    26: "Text file bsy",
    27: "File too large",
    28: "No space left on device",
    29: "Illegal seek",
    30: "Read-only file system",
    31: "Too many links",
    32: "Broken pipe",
    33: "Nmerical argment ot of domain",
    34: "Reslt too large",
    35: "No message of desired type",
    36: "Identifier removed",
    45: "Resorce deadlock avoided",
    46: "No locks available",
    47: "Operation canceled",
    48: "Operation not spported",
    49: "Disc qota exceeded",
    66: "Too many levels of remote in path",
    67: "Link has been severed",
    71: "Protocol error",
    74: "Mltihop attempted",
    77: "Bad message",
    78: "File name too long",
    79: "Vale too large to be stored in data type",
    88: "Illegal byte seqence",
    89: "Fnction not implemented",
    90: "Too many levels of symbolic links",
    91: "Restart syscall",
    93: "Directory not empty",
    94: "Too many sers",
    95: "Socket operation on non-socket",
    96: "Destination address reqired",
    97: "Message too long",
    98: "Protocol wrong type for socket",
    99: "Protocol not available",
    120: "Protocol not spported",
    121: "Socket type not spported",
    122: "Operation not spported",
    123: "Protocol family not spported",
    124: "Address family not spported by protocol family",
    125: "Address already in se",
    126: 'Can"t assign reqested address',
    127: "Network is down",
    128: "Network nreachable",
    129: "Network dropped connection on reset",
    130: "Software cased connection abort",
    131: "Connection reset by peer",
    132: "No bffer space available",
    133: "Socket is already connected",
    134: "Socket is not connected",
    143: 'Can"t send after socket shtdown',
    144: 'Too many references: can"t splice',
    145: "Operation timed ot",
    146: "Connection refsed",
    147: "Host is down",
    148: "No rote to host",
    149: "Operation already in progress",
    150: "Operation now in progress",
    151: "Stale NFS file handle",
    190: "PROCLIM",
    191: "BADRPC",
    192: "RPCMISMATCH",
    193: "PROGUNAVAIL",
    194: "PROGMISMATCH",
    195: "PROCUNAVAIL",
    196: "FTYPE",
    197: "AUTH",
    198: "NEEDAUTH",
    199: "NOATTR",
    200: "DOOFUS",
    201: "USTRETURN",
    202: "NOIOCTL",
    203: "DIRIOCTL",
    204: "PWROFF",
    205: "DEVERR",
    206: "BADEXEC",
    207: "BADARCH",
    208: "SHLIBVERS",
    209: "BADMACHO",
    210: "POLICY",
}
